version: '3.9'

services:
  drupal:
    image: drupal:10.1
    container_name: drupal
    ports:
      - "8080:80" 
    volumes:
      - drupal_data:/var/www/html
    environment:
      - DRUPAL_DB_HOST=db
      - DRUPAL_DB_USER=drupal
      - DRUPAL_DB_PASSWORD=drupal
      - DRUPAL_DB_NAME=drupal
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: drupal_db
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    volumes:
      - db_data:/var/lib/mysql

volumes:
  drupal_data:
  db_data:
